[UPSTREAM] [LLDB] Fix compilation for MinGW, remove redundant class name on inline member
This fixes build errors like these:

NativeRegisterContextWindows.h:22:33: error: extra qualification on member 'NativeRegisterContextWindows'
  NativeRegisterContextWindows::NativeRegisterContextWindows(
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^

Differential Revision: https://reviews.llvm.org/D67856

Change-Id: I6257927879a92a0d48b740a0f956379e011f5acc
llvm-svn: 372482
(cherry picked from commit f4deacf995c73045a2172f35cbaf289fa97e7abc)